{
  "http_port": {{ http_port }},
  "imports_service_url": "{{ imports_service_url }}",
  "docxgenerator_service_url": "{{ docxgenerator_service_url }}",
  "download_export_bucket": "{{ download_export_bucket }}",
  "statics_bucket": "{{ statics_bucket }}",
  "upload_bucket": "{{ upload_bucket }}",
  "document_bucket": "{{ document_bucket }}",
  "form_bucket": "{{ form_bucket }}",
  "template_bucket": "{{ template_bucket }}",
  "import_upload_bucket": "{{ import_upload_bucket }}",
  "api_user_header": "{{ api_user_header }}",
  "api_company_header": "{{ api_company_header }}",
  "generated_output_bucket": "{{ generated_output_bucket }}",
  "automations_form_updates_sqs_url": "{{ automations_form_updates_sqs_url }}",
  "system_jwt_secret_name": "{{ system_jwt_secret_name }}",
  "supio_cloudfront_training_data_config_secret_name": "{{ supio_cloudfront_training_data_config_secret_name }}",
  "metrics_sample_rate": "{{ metrics_sample_rate }}",
  "secrets": {
    "jwt": "{{ secret('jwt') }}",
    "sellersource_header_key": "{{ secret('sellersource_header_key') }}",
    "filethis_api": "{{ secret('filethis_api') }}",
    "clio_app": "{{ secret('clio_app') }}",
    "leaddocket_app": "{{ secret('leaddocket_app') }}",
    "filevine_app": "{{ secret('filevine_app') }}",
    "salesforce_app": "{{ secret('salesforce_app') }}",
    "stripe": "{{ secret('stripe') }}",
    "onedrive_app": "{{ secret('onedrive_app') }}",
    "dropbox_app": "{{ secret('dropbox_app') }}",
    "models_postgres_dev": "{{ secret('models_postgres_dev') }}",
    "growpath_app": "{{ secret('growpath_app') }}",
    "smartadvocate_app": "{{ secret('smartadvocate_app') }}",
    "workato": "{{ secret('workato') }}",
    "microsoft": "{{ secret('microsoft') }}",
    "sharepoint_app": "{{ secret('sharepoint_app') }}"
  }
}
